# permissions for end users to view replicasnums.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: replicas-num
    app.kubernetes.io/managed-by: kustomize
  name: replicasnum-viewer-role
rules:
- apiGroups:
  - web.github.com
  resources:
  - replicasnums
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - web.github.com
  resources:
  - replicasnums/status
  verbs:
  - get
